name: safety-warp
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  # Core Python
  - python=3.11
  - pip

  # PyTorch (CUDA 11.8)
  - pytorch::pytorch::*=py311_cuda11.8*
  - pytorch::pytorch-cuda=11.8
  - pytorch::pytorch-lightning
  
  # Scientific computing
  - numpy>=1.24.0
  - scipy>=1.11.0
  - scikit-learn>=1.3.0
  - pandas>=2.0.0
  
  # Utilities
  - tqdm>=4.66.0
  - pyyaml
  - jinja2
  
  # Development
  - ipython
  - jupyter
  - black
  - flake8
  
  # pip dependencies (for packages not in conda)
  - pip
  - pip:
    - transformers>=4.36.0
    - datasets>=2.14.0
    - huggingface-hub>=0.17.0
    - peft>=0.4.0
    - trl>=0.7.0
    - accelerate>=0.24.0
    - bfloat16
