default_method_hyperparameters:
  # ===== Generation configs ======
  attack_gen_config:
    max_new_tokens: 2048
    temperature: 1.0
    stop_tokens: ['|']

top_5:
  attack_model:
    model_name_or_path: mistralai/Mistral-7B-Instruct-v0.2
    use_vllm: True
    num_gpus: 1
    dtype: bfloat16
    gpu_memory_utilization: 0.9
    max_model_len: 4096
  top_k_persuasion_taxonomy: 5

full_40:
  attack_model:
    model_name_or_path: mistralai/Mistral-7B-Instruct-v0.2
    use_vllm: True
    num_gpus: 1
    dtype: bfloat16
    gpu_memory_utilization: 0.9
    max_model_len: 4096
  top_k_persuasion_taxonomy: 40